package com.alvarosega.trackingventas.ui.saneamiento

object SaneamientoConstants {
    val TIPOS_NEGOCIO = listOf(
        "TDB A", "TDB B", "TDB C", "MINORISTA", "CASETA", "FERIA",
        "FRIAL O CARNICERIA", "ABARROTES", "MAYORISTA", "SUPERMERCADO",
        "MICROMERCADO", "ALMACEN", "ALMACEN DE LIMPIEZA", "FARMACIA ZONAL",
        "CADENA DE FARMACIAS", "HOTEL, MOTEL, ALOJAMIENTO", "HOSPITAL, POSTA MEDICA",
        "UNIVERSIDAD O COLEGIO", "EMPRESAS, BANCOS, COOPERATIVAS, SINDICATOS",
        "RESTAURANTE, PENSIÓN O CAFETERIA", "PELUQUERIA", "LAVANDERIA",
        "LICORERIA", "ESTACION DE SERVICIO", "BALNEARIO O PISCINA",
        "VENTA OFICINA", "FRIAL Y CARNICERIA - TDB", "FRIAL Y CARNICERIA - MZO",
        "CASETA - TDB", "CASETA - MZO", "PROVINCIA", "Prov. MAY", "Prov MZO"
    )

    val ZONAS = listOf(
        "12 DE OCTUBRE", "16 DE JULIO", "ALTO LIMA A", "ALTO LIMA B", "ALTO LIMA C",
        "AV LITORAL", "BALLIVIAN", "BAUTISTA SAAVEDRA", "CALAMA", "CEJA", "CENTRAL",
        "CIUDAD SATELITE", "CONVIFAG", "COSMOS 78", "COSMOS 79 A", "HORIZONTES",
        "HORIZONTES II", "KENKO", "LAGUNAS", "LOS ANDES", "MERCURIO", "ORO NEGRO",
        "PACAJES", "RIO SECO A", "SAN MARTIN", "SAN ROQUE A", "SANTIAGO II",
        "SENKATA", "TAWANTINSUYO", "TUNARI", "TUNARI A", "VENTILLA", "VILLA ADELA",
        "VILLA DOLORES", "VILLA ESPERANZA", "VILLA INGENIO", "VILLA INGENIO A",
        "VILLA MERCEDES", "YUNGUYO A", "YUNGUYO B", "ZONA BRASIL"
    )
}